Repository kubernetes-sigs/kube-api-linter, pull requests merged in 2025-04, with the labels that each got.

#56 integrate error variable of KAL
  pkg/analysis/commentstart/analyzer.go
  pkg/analysis/conditions/analyzer.go
  pkg/analysis/errors/errors.go
  pkg/analysis/helpers/extractjsontags/analyzer.go
  pkg/analysis/helpers/inspector/analyzer.go
  pkg/analysis/helpers/markers/analyzer.go
  pkg/analysis/integers/analyzer.go
  pkg/analysis/jsontags/analyzer.go
  pkg/analysis/maxlength/analyzer.go
  pkg/analysis/nobools/analyzer.go
  pkg/analysis/nofloats/analyzer.go
  pkg/analysis/nomaps/analyzer.go
  pkg/analysis/nophase/analyzer.go
  pkg/analysis/optionalorrequired/analyzer.go
  pkg/analysis/requiredfields/analyzer.go
  pkg/analysis/statussubresource/analyzer.go
Labels: cncf-cla: yes, size/L, approved, lgtm, kind/cleanup

#60 owners: add everettraven as a reviewer
  OWNERS
Labels: cncf-cla: yes, approved, size/XS, lgtm

#67 Add initial security contacts
  SECURITY_CONTACTS
Labels: cncf-cla: yes, approved, lgtm, size/S

#62 check if type spec has optional or required marker
  README.md
  pkg/analysis/helpers/inspector/inspector.go
  pkg/analysis/optionalorrequired/analyzer.go
  pkg/analysis/optionalorrequired/analyzer_test.go
  pkg/analysis/optionalorrequired/doc.go
  pkg/analysis/optionalorrequired/testdata/src/c/c.go
  pkg/analysis/optionalorrequired/testdata/src/c/c.go.golden
Labels: cncf-cla: yes, size/L, approved, lgtm

#63 modernize sources
  .github/workflows/lint.yaml
  Makefile
  go.mod
  go.sum
  pkg/analysis/commentstart/analyzer.go
  pkg/analysis/conditions/analyzer.go
  pkg/analysis/helpers/extractjsontags/analyzer.go
  pkg/analysis/helpers/inspector/analyzer.go
  pkg/analysis/helpers/inspector/analyzer_test.go
  pkg/analysis/helpers/markers/analyzer.go
  pkg/analysis/integers/analyzer.go
  pkg/analysis/jsontags/analyzer.go
  pkg/analysis/maxlength/analyzer.go
  pkg/analysis/nobools/analyzer.go
  pkg/analysis/nofloats/analyzer.go
  pkg/analysis/nophase/analyzer.go
  pkg/analysis/optionalorrequired/analyzer.go
  pkg/analysis/requiredfields/analyzer.go
  pkg/analysis/statussubresource/analyzer.go
  pkg/analysis/utils/type_check_test.go
  tools/go.mod
  tools/go.sum
Labels: cncf-cla: yes, size/L, approved, lgtm, kind/cleanup

#71 Ensure type declarations are picked up across file boundaries
  pkg/analysis/helpers/inspector/analyzer.go
  pkg/analysis/integers/testdata/src/a/a.go
  pkg/analysis/integers/testdata/src/a/b.go
  pkg/analysis/maxlength/analyzer.go
  pkg/analysis/maxlength/testdata/src/a/a.go
  pkg/analysis/maxlength/testdata/src/a/b.go
  pkg/analysis/nobools/testdata/src/a/a.go
  pkg/analysis/nobools/testdata/src/a/b.go
  pkg/analysis/nofloats/testdata/src/a/a.go
  pkg/analysis/nofloats/testdata/src/a/b.go
  pkg/analysis/nomaps/testdata/src/a/a.go
  pkg/analysis/nomaps/testdata/src/a/b.go
  pkg/analysis/utils/testdata/src/a/a.go
  pkg/analysis/utils/testdata/src/a/b.go
  pkg/analysis/utils/type_check.go
  pkg/analysis/utils/utils.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#75 Skip reporting issues on Items style structs
  pkg/analysis/helpers/inspector/inspector.go
  pkg/analysis/helpers/inspector/testdata/src/a/a.go
  pkg/analysis/helpers/inspector/testdata/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
  pkg/analysis/helpers/inspector/testdata/src/k8s.io/apimachinery/pkg/types/types.go
Labels: cncf-cla: yes, size/L, approved, lgtm
