Repository kubernetes-sigs/kube-api-linter, pull requests merged in 2025-05, with the labels that each got.

#76 Add declarative validation linting to optionalorrequired
  pkg/analysis/optionalorrequired/analyzer.go
  pkg/analysis/optionalorrequired/testdata/src/a/a.go
  pkg/analysis/optionalorrequired/testdata/src/a/a.go.golden
  pkg/analysis/optionalorrequired/testdata/src/c/c.go
  pkg/analysis/optionalorrequired/testdata/src/c/c.go.golden
Labels: cncf-cla: yes, size/L, approved, lgtm

#77 k8s:optional and k8s:required should be lowercase
  pkg/analysis/optionalorrequired/analyzer.go
  pkg/analysis/optionalorrequired/testdata/src/a/a.go
  pkg/analysis/optionalorrequired/testdata/src/a/a.go.golden
  pkg/analysis/optionalorrequired/testdata/src/c/c.go
  pkg/analysis/optionalorrequired/testdata/src/c/c.go.golden
Labels: cncf-cla: yes, approved, lgtm, size/M

#74 unify marker definitions to markers package
  pkg/analysis/maxlength/analyzer.go
  pkg/analysis/optionalorrequired/analyzer.go
  pkg/analysis/optionalorrequired/analyzer_test.go
  pkg/analysis/requiredfields/analyzer.go
  pkg/analysis/statussubresource/analyzer.go
  pkg/markers/markers.go
  pkg/validation/linters_config.go
  pkg/validation/linters_config_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, kind/cleanup

#78 Add golangci-lint Go plugin version of KAL
  README.md
  pkg/plugin/plugin.go
  plugin.go
Labels: cncf-cla: yes, approved, lgtm, size/M

#79 add FieldName API
  pkg/analysis/commentstart/analyzer.go
  pkg/analysis/helpers/inspector/analyzer_test.go
  pkg/analysis/jsontags/analyzer.go
  pkg/analysis/maxlength/analyzer.go
  pkg/analysis/nomaps/analyzer.go
  pkg/analysis/nophase/analyzer.go
  pkg/analysis/optionalorrequired/analyzer.go
  pkg/analysis/requiredfields/analyzer.go
  pkg/analysis/utils/type_check.go
  pkg/analysis/utils/utils.go
  pkg/analysis/utils/utils_suite_test.go
  pkg/analysis/utils/utils_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#61 add duplicatemarkers linter
  README.md
  pkg/analysis/duplicatemarkers/analyzer.go
  pkg/analysis/duplicatemarkers/analyzer_test.go
  pkg/analysis/duplicatemarkers/doc.go
  pkg/analysis/duplicatemarkers/initializer.go
  pkg/analysis/duplicatemarkers/testdata/src/a/a.go
  pkg/analysis/duplicatemarkers/testdata/src/a/a.go.golden
  pkg/analysis/duplicatemarkers/testdata/src/a/go.mod
  pkg/analysis/duplicatemarkers/testdata/src/a/go.sum
  pkg/analysis/registry.go
  pkg/analysis/registry_test.go
Labels: cncf-cla: yes, approved, lgtm, size/XL

#73 Add statusoptional linter
  README.md
  go.sum
  pkg/analysis/registry.go
  pkg/analysis/registry_test.go
  pkg/analysis/statusoptional/analyzer.go
  pkg/analysis/statusoptional/analyzer_test.go
  pkg/analysis/statusoptional/doc.go
  pkg/analysis/statusoptional/initializer.go
  pkg/analysis/statusoptional/testdata/src/a/a.go
  pkg/analysis/statusoptional/testdata/src/a/a.go.golden
  pkg/analysis/statusoptional/testdata/src/b/b.go
  pkg/analysis/statusoptional/testdata/src/b/b.go.golden
  pkg/analysis/statusoptional/testdata/src/c/c.go
  pkg/analysis/statusoptional/testdata/src/c/c.go.golden
  pkg/config/linters_config.go
  pkg/validation/linters_config.go
  pkg/validation/linters_config_test.go
Labels: cncf-cla: yes, approved, lgtm, size/XL

#84 Account for types from other files in statusoptional/duplicatemarkers
  pkg/analysis/duplicatemarkers/analyzer.go
  pkg/analysis/duplicatemarkers/testdata/src/a/a.go
  pkg/analysis/duplicatemarkers/testdata/src/a/a.go.golden
  pkg/analysis/duplicatemarkers/testdata/src/a/b.go
  pkg/analysis/duplicatemarkers/testdata/src/a/go.mod
  pkg/analysis/duplicatemarkers/testdata/src/a/go.sum
  pkg/analysis/statusoptional/analyzer.go
  pkg/analysis/statusoptional/testdata/src/a/a.go
  pkg/analysis/statusoptional/testdata/src/a/a.go.golden
  pkg/analysis/statusoptional/testdata/src/a/b.go
Labels: kind/bug, cncf-cla: yes, size/L, approved, lgtm

#91 statusoptional: Embed nil check in checkStatusStruct
  pkg/analysis/statusoptional/analyzer.go
Labels: cncf-cla: yes, approved, size/XS, lgtm
