Repository kubernetes-sigs/kube-api-linter, pull requests merged in 2025-06, with the labels that each got.

#94 add uniquemarkers linter
  README.md
  pkg/analysis/duplicatemarkers/analyzer.go
  pkg/analysis/optionalfields/util.go
  pkg/analysis/uniquemarkers/analyzer.go
  pkg/analysis/uniquemarkers/analyzer_test.go
  pkg/analysis/uniquemarkers/doc.go
  pkg/analysis/uniquemarkers/initializer.go
  pkg/analysis/uniquemarkers/testdata/src/a/a.go
  pkg/analysis/uniquemarkers/testdata/src/b/b.go
  pkg/analysis/utils/utils.go
  pkg/config/linters_config.go
  pkg/markers/markers.go
  pkg/validation/linters_config.go
Labels: cncf-cla: yes, approved, size/XXL, lgtm

#98 analysis: add uniquemarkers to registry
  pkg/analysis/registry.go
  pkg/analysis/registry_test.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#104 docs: move linters to a dedicated file
  README.md
  docs/linters.md
  docs/new-linter.md
Labels: cncf-cla: yes, approved, lgtm, size/XL

#103 markers: fix a bug when parsing expressions with commas present in value
  pkg/analysis/helpers/markers/analyzer.go
  pkg/analysis/helpers/markers/analyzer_test.go
Labels: cncf-cla: yes, approved, lgtm, size/M
